#!/bin/bash

current=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
available=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors | sed 's/ /\n/g')
gov=$(printf "$available" | dmenu -p "Please select a CPU governor, [$current] is active:")

if [[ -z $gov ]]; then
	exit
else
	sudo -A cpupower frequency-set -g $gov
fi
